/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Principal.peliculas;
import static Ventanas.Principal.codigos;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefani
 */
public class Alquilar_pelicula extends javax.swing.JFrame {

    /**
     * Creates new form Alquilar_pelicula
     */
    public static Principal principal_4;
    public Alquilar_pelicula(Principal princ) {
        initComponents();
        principal_4 = princ;
        principal_4.setVisible(false);
        todas_las_peliculas.setText(peliculas.DatosPeliculas());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        todas_las_peliculas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        nro_socio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        alquilar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        todas_las_peliculas.setEditable(false);
        todas_las_peliculas.setColumns(20);
        todas_las_peliculas.setRows(5);
        jScrollPane1.setViewportView(todas_las_peliculas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 280, 260));

        jLabel1.setText("Nro de socio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel1.add(nro_socio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, -1));

        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, -1));

        alquilar.setText("Alquilar pelicula");
        alquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquilarActionPerformed(evt);
            }
        });
        jPanel1.add(alquilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel3.setText("Dias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel1.add(dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        principal_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void alquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilarActionPerformed
        if (codigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo de la pelicula.");
            codigo.setText("");
        }else if(nro_socio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar su nro de socio.");
            nro_socio.setText("");
        }else if(dias.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el numero de dias que desea alquilar la pelicula.");
            dias.setText("");
        }else{
            int posicion = codigos.BusquedaBinaria(Integer.parseInt(codigo.getText()));
            if (posicion > -1) {
                try {
                   int nro_dias = Integer.parseInt(dias.getText());
                   try {
                        int nro_socio_int = Integer.parseInt(nro_socio.getText());
                        JOptionPane.showMessageDialog(this, peliculas.Alquilar(posicion, nro_dias, nro_socio_int));
                        principal_4.setVisible(true);
                        this.dispose();
                     } catch (Exception err) {
                         JOptionPane.showMessageDialog(this, "Por favor ingrese su numero de socio.");
                     }
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this, "Por favor el numero de dias que desea alquilar la pelicula.");
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Debe ingresar un codigo existente.");
            }
        }
    }//GEN-LAST:event_alquilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alquilar_pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alquilar_pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alquilar_pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alquilar_pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alquilar_pelicula(principal_4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alquilar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField dias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nro_socio;
    private javax.swing.JButton salir;
    private javax.swing.JTextArea todas_las_peliculas;
    // End of variables declaration//GEN-END:variables
}
